require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe GregSucksController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # GregSuck. As you add validations to GregSuck, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # GregSucksController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all greg_sucks as @greg_sucks" do
      greg_suck = GregSuck.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:greg_sucks)).to eq([greg_suck])
    end
  end

  describe "GET show" do
    it "assigns the requested greg_suck as @greg_suck" do
      greg_suck = GregSuck.create! valid_attributes
      get :show, {:id => greg_suck.to_param}, valid_session
      expect(assigns(:greg_suck)).to eq(greg_suck)
    end
  end

  describe "GET new" do
    it "assigns a new greg_suck as @greg_suck" do
      get :new, {}, valid_session
      expect(assigns(:greg_suck)).to be_a_new(GregSuck)
    end
  end

  describe "GET edit" do
    it "assigns the requested greg_suck as @greg_suck" do
      greg_suck = GregSuck.create! valid_attributes
      get :edit, {:id => greg_suck.to_param}, valid_session
      expect(assigns(:greg_suck)).to eq(greg_suck)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new GregSuck" do
        expect {
          post :create, {:greg_suck => valid_attributes}, valid_session
        }.to change(GregSuck, :count).by(1)
      end

      it "assigns a newly created greg_suck as @greg_suck" do
        post :create, {:greg_suck => valid_attributes}, valid_session
        expect(assigns(:greg_suck)).to be_a(GregSuck)
        expect(assigns(:greg_suck)).to be_persisted
      end

      it "redirects to the created greg_suck" do
        post :create, {:greg_suck => valid_attributes}, valid_session
        expect(response).to redirect_to(GregSuck.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved greg_suck as @greg_suck" do
        post :create, {:greg_suck => invalid_attributes}, valid_session
        expect(assigns(:greg_suck)).to be_a_new(GregSuck)
      end

      it "re-renders the 'new' template" do
        post :create, {:greg_suck => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested greg_suck" do
        greg_suck = GregSuck.create! valid_attributes
        put :update, {:id => greg_suck.to_param, :greg_suck => new_attributes}, valid_session
        greg_suck.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested greg_suck as @greg_suck" do
        greg_suck = GregSuck.create! valid_attributes
        put :update, {:id => greg_suck.to_param, :greg_suck => valid_attributes}, valid_session
        expect(assigns(:greg_suck)).to eq(greg_suck)
      end

      it "redirects to the greg_suck" do
        greg_suck = GregSuck.create! valid_attributes
        put :update, {:id => greg_suck.to_param, :greg_suck => valid_attributes}, valid_session
        expect(response).to redirect_to(greg_suck)
      end
    end

    describe "with invalid params" do
      it "assigns the greg_suck as @greg_suck" do
        greg_suck = GregSuck.create! valid_attributes
        put :update, {:id => greg_suck.to_param, :greg_suck => invalid_attributes}, valid_session
        expect(assigns(:greg_suck)).to eq(greg_suck)
      end

      it "re-renders the 'edit' template" do
        greg_suck = GregSuck.create! valid_attributes
        put :update, {:id => greg_suck.to_param, :greg_suck => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested greg_suck" do
      greg_suck = GregSuck.create! valid_attributes
      expect {
        delete :destroy, {:id => greg_suck.to_param}, valid_session
      }.to change(GregSuck, :count).by(-1)
    end

    it "redirects to the greg_sucks list" do
      greg_suck = GregSuck.create! valid_attributes
      delete :destroy, {:id => greg_suck.to_param}, valid_session
      expect(response).to redirect_to(greg_sucks_url)
    end
  end

end
